[package]
name = "shran"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
ansi_term = "0.12.1"
octocrab = "0.13.0"
indicatif = "0.16.2"
serde = "1.0"
serde_yaml = "0.8"
